const PREFIX = 'examples/LocationExample/';
export const GEOLOCATION = PREFIX + 'GEOLOCATION';
export const GEOLOCATION_DETECTION = PREFIX + 'GEOLOCATION_DETECTION';
export const CHANGE_CURRENT_LOCATION = PREFIX + 'CHANGE_CURRENT_LOCATION';
export const GEOLOCATION_ERROR = PREFIX + 'GEOLOCATION_ERROR';
